-- OpoCoach Web - esquema inicial multiusuario
-- Contenidos: siguen en oposiciones.sqlite3 (solo lectura).
-- Esta base PostgreSQL almacena exclusivamente identidad, suscripción y actividad de usuarios.

BEGIN;

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text,
    nombre text,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    proveedor text NOT NULL DEFAULT 'STRIPE',
    customer_id text,
    subscription_id text,
    plan text,
    status text NOT NULL DEFAULT 'SIN_SUSCRIPCION',
    current_period_end timestamptz,
    cancel_at_period_end boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_subscriptions_subscription_id UNIQUE (subscription_id)
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id
    ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_customer_id
    ON public.subscriptions(customer_id);

CREATE TABLE IF NOT EXISTS public.simulacros (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    convocatoria_id integer NOT NULL,
    numero integer NOT NULL,
    fecha_generacion timestamptz NOT NULL DEFAULT now(),
    total_preguntas integer NOT NULL CHECK (total_preguntas > 0),
    estado text NOT NULL DEFAULT 'GENERADO'
        CHECK (estado IN ('GENERADO', 'FINALIZADO', 'ANULADO')),
    tipo_prueba text NOT NULL DEFAULT 'SIMULACRO'
        CHECK (tipo_prueba IN ('SIMULACRO', 'TEST')),
    finalizado_at timestamptz,

    -- Configuración de convocatoria congelada en el momento de crear la prueba.
    convocatoria_codigo text,
    convocatoria_puesto text,
    convocatoria_numero text,
    convocatoria_anio integer,
    convocatoria_numero_preguntas integer,
    valoracion_test_acierto double precision,
    valoracion_test_fallo double precision,
    valoracion_test_no_contesta double precision,
    formula_nota text,
    factor_escala_nota double precision,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_simulacros_usuario_convocatoria_numero
        UNIQUE (user_id, convocatoria_id, tipo_prueba, numero)
);

CREATE INDEX IF NOT EXISTS idx_simulacros_user_id
    ON public.simulacros(user_id);
CREATE INDEX IF NOT EXISTS idx_simulacros_user_convocatoria
    ON public.simulacros(user_id, convocatoria_id, tipo_prueba, fecha_generacion DESC);

CREATE TABLE IF NOT EXISTS public.simulacro_preguntas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulacro_id bigint NOT NULL REFERENCES public.simulacros(id) ON DELETE CASCADE,
    orden integer NOT NULL CHECK (orden > 0),

    -- Identificadores de la base de contenidos. No son FK porque viven en SQLite.
    pregunta_id integer,
    banco_pregunta_id integer,
    parte_id integer,
    parte_nombre text,
    parte_orden integer,

    respuesta_usuario text CHECK (respuesta_usuario IS NULL OR respuesta_usuario IN ('A','B','C','D')),
    seguridad_usuario text CHECK (
        seguridad_usuario IS NULL OR
        seguridad_usuario IN ('MUY_SEGURO','BASTANTE_SEGURO','POCO_SEGURO')
    ),

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_simulacro_preguntas_orden UNIQUE (simulacro_id, orden)
);

CREATE INDEX IF NOT EXISTS idx_simulacro_preguntas_simulacro_id
    ON public.simulacro_preguntas(simulacro_id);
CREATE INDEX IF NOT EXISTS idx_simulacro_preguntas_pregunta_id
    ON public.simulacro_preguntas(pregunta_id);

CREATE TABLE IF NOT EXISTS public.simulacro_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulacro_pregunta_id bigint NOT NULL UNIQUE
        REFERENCES public.simulacro_preguntas(id) ON DELETE CASCADE,

    enunciado text NOT NULL,
    opcion_a text NOT NULL,
    opcion_b text NOT NULL,
    opcion_c text NOT NULL,
    opcion_d text NOT NULL,
    respuesta_correcta text NOT NULL CHECK (respuesta_correcta IN ('A','B','C','D')),

    tipo_clasificacion text NOT NULL,
    tipo_norma text,
    nombre_norma text,
    articulo text,
    tema_no_juridico text,
    origen_oposicion text,
    tipo_fuente text NOT NULL,
    importacion_fichero_id integer,
    pagina_origen integer,
    norma_id_normalizada integer,
    articulo_normalizado text,
    teorica_practica text,
    tipo_norma_normalizado text,
    nombre_norma_normalizado text,
    banco_tipo_vinculacion text,
    banco_estado text,
    banco_metodo_vinculacion text,
    banco_motivo_revision text,
    temas_json jsonb,
    comentario_solucion text,

    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_simulacro_snapshot_norma_articulo
    ON public.simulacro_snapshot(nombre_norma_normalizado, articulo_normalizado);

-- Crea automáticamente el perfil al darse de alta un usuario en Supabase Auth.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (id, email, nombre)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data ->> 'nombre', NEW.raw_user_meta_data ->> 'full_name')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Row Level Security. El backend seguirá comprobando user_id, pero estas políticas
-- dejan preparada una segunda barrera para el futuro frontend autenticado.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulacros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulacro_preguntas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulacro_snapshot ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profiles_select_own ON public.profiles;
CREATE POLICY profiles_select_own ON public.profiles
FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS profiles_update_own ON public.profiles;
CREATE POLICY profiles_update_own ON public.profiles
FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS subscriptions_select_own ON public.subscriptions;
CREATE POLICY subscriptions_select_own ON public.subscriptions
FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS simulacros_select_own ON public.simulacros;
CREATE POLICY simulacros_select_own ON public.simulacros
FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS simulacro_preguntas_select_own ON public.simulacro_preguntas;
CREATE POLICY simulacro_preguntas_select_own ON public.simulacro_preguntas
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.simulacros s
        WHERE s.id = simulacro_id AND s.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS simulacro_snapshot_select_own ON public.simulacro_snapshot;
CREATE POLICY simulacro_snapshot_select_own ON public.simulacro_snapshot
FOR SELECT USING (
    EXISTS (
        SELECT 1
        FROM public.simulacro_preguntas sp
        JOIN public.simulacros s ON s.id = sp.simulacro_id
        WHERE sp.id = simulacro_pregunta_id AND s.user_id = auth.uid()
    )
);

COMMIT;
