"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Proceso = { id:number; organismo_nombre:string; denominacion:string; tipo_proceso:string|null; plazas:number|null; estado:string|null; anio_convocatoria:number|null; fecha_apertura:string|null; fecha_cierre:string|null; url_oficial:string|null };
type Suscripcion = { id:number; proceso_id:number; organismo_nombre:string; denominacion:string; tipo_proceso:string|null; plazas:number|null; estado:string|null; anio_convocatoria:number|null; fecha_apertura:string|null; fecha_cierre:string|null; url_oficial:string|null };
type Novedad = { id:number; proceso_id:number; denominacion:string; organismo_nombre:string; novedad_tipo:"PUBLICACION"|"CAMBIO"; tipo:string|null; campo:string|null; resumen:string|null; detectado_at:string|null; significativo:boolean; url:string|null };
type EstadoNovedad = { ultima_novedad_vista_at:string|null };

async function api<T>(path:string, token:string, init?:RequestInit):Promise<T>{const r=await fetch(`/api/empleo/${path.replace(/^\/+/,"")}`,{cache:"no-store",...init,headers:{Authorization:`Bearer ${token}`,...(init?.headers||{})}});const t=await r.text();let b:unknown=null;try{b=t?JSON.parse(t):null}catch{b=t}if(!r.ok)throw new Error(b&&typeof b==='object'&&'detail'in b?String((b as any).detail):`HTTP ${r.status}`);return b as T}
const fecha=(v:string|null)=>{if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("es-ES")};

const CAMPOS_RELEVANTES = new Set(["fecha_apertura","fecha_cierre","fecha_examen","estado","plazas","turno","etapa_actual","tipo_proceso","url_oficial"]);
const TIPOS_PUBLICACION = ["convocatoria","bases","admitidos","excluidos","tribunal","fecha","lugar","examen","modificacion","modificación","resultado","calificacion","calificación","nombramiento","adjudicacion","adjudicación","lista"];
function esPublicacionUtil(n:Novedad){const texto=`${n.tipo||""} ${n.resumen||""}`.toLowerCase().trim();if(!texto)return false;if(/\bnavegaci[oó]n\b/.test(texto)&&texto.length<=80)return false;return TIPOS_PUBLICACION.some(x=>texto.includes(x));}
function esCambioUtil(n:Novedad){if(n.novedad_tipo!=="CAMBIO")return false;const campo=(n.campo||"").toLowerCase();if(CAMPOS_RELEVANTES.has(campo))return true;const texto=`${n.tipo||""} ${n.resumen||""}`.toLowerCase();return /(plazo|fecha de examen|fecha examen|lugar de examen|n[uú]mero de plazas|turno|etapa|estado del proceso|tribunal)/i.test(texto);}
function textoNovedad(n:Novedad){if(n.novedad_tipo==="PUBLICACION")return n.resumen||"Nueva publicación oficial";const campo=(n.campo||"").toLowerCase();if(campo==="fecha_examen")return `Nueva fecha de examen: ${n.resumen||"actualizada"}`;if(campo==="fecha_apertura")return `Cambio en la fecha de apertura: ${n.resumen||"actualizada"}`;if(campo==="fecha_cierre")return `Cambio en la fecha de cierre: ${n.resumen||"actualizada"}`;if(campo==="plazas")return `Cambio en el número de plazas: ${n.resumen||"actualizado"}`;if(campo==="turno")return `Cambio de turno: ${n.resumen||"actualizado"}`;if(campo==="estado")return `Cambio de estado: ${n.resumen||"actualizado"}`;if(campo==="etapa_actual")return `Nueva etapa del proceso: ${n.resumen||"actualizada"}`;return n.resumen||n.tipo||"Novedad oficial";}
function etiquetaPublicacion(tipo:string|null){const t=(tipo||"").toLowerCase();if(t==="tribunal")return "TRIBUNAL";if(t==="convocatoria"||t==="bases")return "CONVOCATORIA";return tipo?tipo.toUpperCase().replace(/_/g," "):"PUBLICACIÓN OFICIAL";}

export default function SeguimientoPage(){
 const supabase=useMemo(()=>createClient(),[]);const [items,setItems]=useState<Suscripcion[]>([]);const [oportunidades,setOportunidades]=useState<Proceso[]>([]);const [novedades,setNovedades]=useState<Novedad[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState<number|null>(null);const [tab,setTab]=useState<"seguidas"|"oportunidades">("seguidas");const [estadoNovedad,setEstadoNovedad]=useState<EstadoNovedad>({ultima_novedad_vista_at:null});const [nuevasIds,setNuevasIds]=useState<Set<string>>(new Set());
 async function cargar(){setLoading(true);setError("");try{const {data,error:e}=await supabase.auth.getSession();if(e)throw e;const t=data.session?.access_token;if(!t)throw new Error("Se requiere autenticación.");const [s,p,n,ev]=await Promise.all([api<Suscripcion[]>("suscripciones",t),api<Proceso[]>("procesos",t),api<Novedad[]>("seguimiento/cambios",t),api<EstadoNovedad>("seguimiento/estado",t)]);setItems(s);setOportunidades(p);setNovedades(n);setEstadoNovedad(ev);
   const utiles=n.filter(x=>x.novedad_tipo==="PUBLICACION"?esPublicacionUtil(x):esCambioUtil(x));
   const visto=ev.ultima_novedad_vista_at?new Date(ev.ultima_novedad_vista_at).getTime():0;
   const idsNuevas=ev.ultima_novedad_vista_at?utiles.filter(x=>(x.detectado_at?new Date(x.detectado_at).getTime():0)>visto).map(x=>`${x.novedad_tipo}-${x.id}`):[];
   setNuevasIds(new Set(idsNuevas));
   const ultimo=utiles.reduce((m,x)=>Math.max(m,x.detectado_at?new Date(x.detectado_at).getTime():0),0);
   if(ultimo>0){const vistoHasta=new Date(ultimo).toISOString();const r=await api<EstadoNovedad>("seguimiento/estado/visto",t,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visto_at:vistoHasta})});setEstadoNovedad(r)}
 }catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 useEffect(()=>{void cargar()},[supabase]);
 async function toggle(id:number,seguir:boolean){setBusy(id);setError("");try{const {data}=await supabase.auth.getSession();const t=data.session?.access_token;if(!t)throw new Error("Se requiere autenticación.");await api(`suscripciones/${id}`,t,{method:seguir?"POST":"DELETE"});await cargar()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(null)}}
 const novedadesUtiles=novedades.filter(n=>n.novedad_tipo==="PUBLICACION"?esPublicacionUtil(n):esCambioUtil(n));
 const nuevas=novedadesUtiles.filter(n=>nuevasIds.has(`${n.novedad_tipo}-${n.id}`));
 if(loading)return <main style={s.main}><p>Cargando seguimiento…</p></main>;
 return <main style={s.main}>
  <header style={s.header}><div><div style={s.kicker}>NETRETO</div><h1 style={s.title}>Mi seguimiento</h1><p style={s.subtitle}>Convocatorias que sigues y novedades oficiales relacionadas con ellas.</p></div><a href="/empleo">Volver a Empleo</a></header>
  {error&&<div style={s.error}>{error}</div>}
  <div style={s.tabs}><button style={tab==="seguidas"?s.tabActive:s.tab} onClick={()=>setTab("seguidas")}>Mis convocatorias ({items.length})</button><button style={tab==="oportunidades"?s.tabActive:s.tab} onClick={()=>setTab("oportunidades")}>Buscar convocatorias ({oportunidades.length})</button></div>
  {tab==="seguidas"?<>
   <section style={s.panel}><div style={s.sectionHead}><h2 style={s.h2}>Mis convocatorias</h2><span style={s.muted}>{items.length} seguidas</span></div>
    {items.length===0?<p style={s.muted}>Todavía no sigues ninguna convocatoria.</p>:<div style={s.list}>{items.map(x=><article key={x.id} style={s.card}>
      <div><div style={s.kicker}>{x.organismo_nombre}</div><h3 style={s.cardTitle}>{x.denominacion}</h3><p style={s.muted}>{x.tipo_proceso||"Proceso selectivo"}{x.plazas!=null?` · ${x.plazas} plazas`:""}</p><p style={s.meta}>Inscripción: {fecha(x.fecha_apertura)}{x.fecha_cierre?` · Cierre: ${fecha(x.fecha_cierre)}`:""}</p>{x.url_oficial&&<a href={x.url_oficial} target="_blank" rel="noreferrer">Ver convocatoria oficial ↗</a>}</div>
      <button style={s.secondary} disabled={busy===x.proceso_id} onClick={()=>void toggle(x.proceso_id,false)}>{busy===x.proceso_id?"Guardando…":"Dejar de seguir"}</button>
    </article>)}</div>}
   </section>
   <section style={s.panel}><div style={s.sectionHead}><h2 style={s.h2}>Últimas novedades {nuevas.length>0&&<span style={s.newBadge}>{nuevas.length} nuevas</span>}</h2><span style={s.muted}>{novedadesUtiles.length} novedades</span></div>
    {novedadesUtiles.length===0?<div><p style={s.muted}>No hay novedades relevantes en tus convocatorias.</p><p style={s.hint}>Cuando se publique algo que pueda afectar a tu proceso, aparecerá aquí con su enlace oficial.</p></div>:<div style={s.list}>{novedadesUtiles.map(n=>{const nueva=nuevasIds.has(`${n.novedad_tipo}-${n.id}`);return <article key={`${n.novedad_tipo}-${n.id}`} style={nueva?{...s.change,...s.changeNew}:s.change}>
      <div style={s.kicker}>{n.organismo_nombre} · {fecha(n.detectado_at)}</div>{nueva&&<div style={s.newLabel}>NUEVA</div>}<div style={s.noveltyBadge}>{n.novedad_tipo==="PUBLICACION"?etiquetaPublicacion(n.tipo):"CAMBIO RELEVANTE"}</div><h3 style={s.cardTitle}>{n.denominacion}</h3>
      <p style={s.changeText}>{textoNovedad(n)}</p>{n.url&&<a href={n.url} target="_blank" rel="noreferrer">Abrir fuente oficial ↗</a>}
    </article>})}</div>}
   </section>
  </>:
   <section style={s.panel}><div style={s.sectionHead}><h2 style={s.h2}>Convocatorias activas</h2><span style={s.muted}>{oportunidades.length} oportunidades</span></div><div style={s.list}>{oportunidades.map(x=>{const seguida=items.some(i=>i.proceso_id===x.id);return <article key={x.id} style={s.card}><div><div style={s.kicker}>{x.organismo_nombre}</div><h3 style={s.cardTitle}>{x.denominacion}</h3><p style={s.muted}>{x.tipo_proceso||"Proceso selectivo"}{x.plazas!=null?` · ${x.plazas} plazas`:""}</p><p style={s.meta}>Inscripción: {fecha(x.fecha_apertura)}{x.fecha_cierre?` · Cierre: ${fecha(x.fecha_cierre)}`:""}</p>{x.url_oficial&&<a href={x.url_oficial} target="_blank" rel="noreferrer">Ver convocatoria oficial ↗</a>}</div><button style={seguida?s.follow:s.primary} disabled={busy===x.id} onClick={()=>void toggle(x.id,!seguida)}>{busy===x.id?"Guardando…":seguida?"Siguiendo":"Seguir"}</button></article>})}</div></section>}
 </main>;
}
const s:Record<string,React.CSSProperties>={main:{maxWidth:1100,margin:"0 auto",padding:"32px 20px 56px",fontFamily:"system-ui,sans-serif",color:"#172033"},header:{display:"flex",justifyContent:"space-between",gap:24,alignItems:"flex-start",marginBottom:18},kicker:{fontSize:12,letterSpacing:1.4,fontWeight:700,opacity:.62,marginBottom:6},title:{fontSize:34,margin:0},subtitle:{marginTop:8,opacity:.72},tabs:{display:"flex",gap:8,marginBottom:18},tab:{border:"1px solid #cfd6e2",background:"#fff",borderRadius:8,padding:"9px 12px",cursor:"pointer"},tabActive:{border:"1px solid #172033",background:"#edf2f8",borderRadius:8,padding:"9px 12px",cursor:"pointer",fontWeight:650},panel:{border:"1px solid #d9dee8",borderRadius:14,padding:18,background:"#fff",marginBottom:18},sectionHead:{display:"flex",justifyContent:"space-between",alignItems:"baseline",marginBottom:12},h2:{margin:0,fontSize:20},list:{display:"grid",gap:12},card:{border:"1px solid #e1e5ec",borderRadius:12,padding:16,display:"flex",justifyContent:"space-between",gap:18,alignItems:"center"},change:{borderTop:"1px solid #edf0f4",padding:"13px 0"},changeNew:{background:"#f6f8fb",borderRadius:8,padding:"13px 12px"},cardTitle:{margin:"4px 0 6px",fontSize:17},changeText:{margin:0,lineHeight:1.45},hint:{margin:"4px 0 0",fontSize:12,opacity:.58},muted:{opacity:.68,fontSize:13},meta:{margin:"8px 0",fontSize:13,opacity:.72},noveltyBadge:{fontSize:11,fontWeight:700,letterSpacing:.7,marginBottom:4},newBadge:{display:"inline-block",marginLeft:8,padding:"3px 7px",borderRadius:999,fontSize:11,fontWeight:700,background:"#172033",color:"#fff",verticalAlign:"middle"},newLabel:{display:"inline-block",marginBottom:5,padding:"3px 7px",borderRadius:999,fontSize:10,fontWeight:800,letterSpacing:.8,background:"#172033",color:"#fff"},primary:{border:"1px solid #172033",background:"#172033",color:"#fff",borderRadius:8,padding:"8px 12px",cursor:"pointer",whiteSpace:"nowrap"},follow:{border:"1px solid #9aa6b8",background:"#edf2f8",borderRadius:8,padding:"8px 12px",cursor:"pointer",whiteSpace:"nowrap"},secondary:{border:"1px solid #cfd6e2",background:"#fff",borderRadius:8,padding:"8px 12px",cursor:"pointer",whiteSpace:"nowrap"},error:{marginBottom:18,padding:12,borderRadius:8,border:"1px solid #e2b8b8",background:"#fff6f6"}};