name: Update plazo palabras

on:
  push:
    paths:
      - '.github/workflows/update-plazo-palabras.yml'

permissions:
  contents: write

jobs:
  update:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Actualizar submódulo Empleo
        shell: bash
        run: |
          cd backend/employment_service
          git fetch origin main
          git checkout 8b7c763542e5f966f7a4309d78734a55dc5eb4df
          cd ../..
          git add backend/employment_service
      - name: Commit
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git diff --cached --quiet && exit 0
          git commit -m "Interpretar plazos locales expresados con palabras"
          git push
